import {
  Animal1,
  Animal2,
  Animal3,
  Animal4,
  Animal5,
  Animal6,
  Animal7,
  Animal8,
  Animal9,
  Animal10,
  Animal11,
  Animal12,
  Animal13,
  Animal14,
  Animal15,
  Animal16,
  Animal17,
  Animal18,
  Animal19,
  Animal20,
} from "../assets";

import {
  Animation1,
  Animation2,
  Animation3,
  Animation4,
  Animation5,
  Animation6,
  Animation7,
  Animation8,
  Animation9,
  Animation10,
  Animation11,
  Animation12,
  Animation13,
  Animation14,
  Animation15,
  Animation16,
  Animation17,
  Animation18,
  Animation19,
  Animation20,
} from "../assets";

import {
  Cars1,
  Cars2,
  Cars3,
  Cars4,
  Cars5,
  Cars6,
  Cars7,
  Cars8,
  Cars9,
  Cars10,
  Cars11,
  Cars12,
  Cars13,
  Cars14,
  Cars15,
  Cars16,
  Cars17,
  Cars18,
  Cars19,
  Cars20,
  Cars21,
} from "../assets";

import {
  Specific1,
  Specific2,
  Specific3,
  Specific4,
  Specific5,
  Specific6,
  Specific7,
  Specific8,
  Specific9,
  Specific10,
  Specific11,
  Specific12,
  Specific13,
  Specific14,
  Specific15,
  Specific16,
  Specific17,
  Specific18,
  Specific19,
  Specific20,
  Specific21,
} from "../assets";

export const photos = [
  { category: "animals", name: "chameleons", src: Animal1 , cname : 'Animal1'},
  { category: "animals", name: "parrot", src: Animal2 , cname : 'Animal2'},
  { category: "animals", name: "dog", src: Animal3 , cname : 'Animal3'},
  { category: "animals", name: "cat", src: Animal4 , cname : 'Animal4'},
  { category: "animals", name: "butterfly", src: Animal5 , cname : 'Animal5'},
  { category: "animals", name: "tiger", src: Animal6 , cname : 'Animal6'},
  { category: "animals", name: "tiger", src: Animal7 , cname : 'Animal7'},
  { category: "animals", name: "wolf", src: Animal8 , cname : 'Animal8'},
  { category: "animals", name: "cat", src: Animal9 , cname : 'Animal9'},
  { category: "animals", name: "cat", src: Animal10 , cname : 'Animal10'},
  { category: "animals", name: "wolf", src: Animal11 , cname : 'Animal11'},
  { category: "animals", name: "dog", src: Animal12 , cname : 'Animal12'},
  { category: "animals", name: "tiger", src: Animal13 , cname : 'Animal13'},
  { category: "animals", name: "jellyfish", src: Animal14 , cname : 'Animal14'},
  { category: "animals", name: "canary", src: Animal15 , cname : 'Animal15'},
  { category: "animals", name: "cat", src: Animal16 , cname : 'Animal16'},
  { category: "animals", name: "tiger", src: Animal17 , cname : 'Animal17'},
  { category: "animals", name: "cat", src: Animal18 , cname : 'Animal18'},
  { category: "animals", name: "cat", src: Animal19 , cname : 'Animal19'},
  { category: "animals", name: "tiger", src: Animal20 , cname : 'Animal20'},

  { category: "animation", name: "dark", src: Animation1 , cname : 'Animation1'},
  { category: "animation", name: "day", src: Animation2 , cname : 'Animation2'},
  { category: "animation", name: "shining", src: Animation3 , cname : 'Animation3'},
  { category: "animation", name: "dark", src: Animation4 , cname : 'Animation4'},
  { category: "animation", name: "landscape", src: Animation5 , cname : 'Animation5'},
  { category: "animation", name: "avatar", src: Animation6 , cname : 'Animation6'},
  { category: "animation", name: "water", src: Animation7 , cname : 'Animation7'},
  { category: "animation", name: "pingu", src: Animation8 , cname : 'Animation8'},
  { category: "animation", name: "christmas", src: Animation9 , cname : 'Animation9'},
  { category: "animation", name: "dark", src: Animation10 , cname : 'Animation10'},
  { category: "animation", name: "green", src: Animation11 , cname : 'Animation11'},
  { category: "animation", name: "ocean", src: Animation12 , cname : 'Animation12'},
  { category: "animation", name: "earth", src: Animation13 , cname : 'Animation13'},
  { category: "animation", name: "day", src: Animation14 , cname : 'Animation14'},
  { category: "animation", name: "box", src: Animation15 , cname : 'Animation15'},
  { category: "animation", name: "dark", src: Animation16 , cname : 'Animation16'},
  { category: "animation", name: "dark", src: Animation17 , cname : 'Animation17'},
  { category: "animation", name: "robot", src: Animation18 , cname : 'Animation18'},
  { category: "animation", name: "iron man", src: Animation19 , cname : 'Animation19'},
  { category: "animation", name: "cars", src: Animation20 , cname : 'Animation20'},

  { category: "cars", name: "car", src: Cars1 , cname : 'Cars1'},
  { category: "cars", name: "car", src: Cars2 , cname : 'Cars2'},
  { category: "cars", name: "car", src: Cars3 , cname : 'Cars3'},
  { category: "cars", name: "car", src: Cars4 , cname : 'Cars4'},
  { category: "cars", name: "car", src: Cars5 , cname : 'Cars5'},
  { category: "cars", name: "car", src: Cars6 , cname : 'Cars6'},
  { category: "cars", name: "car", src: Cars7 , cname : 'Cars7'},
  { category: "cars", name: "car", src: Cars8 , cname : 'Cars8'},
  { category: "cars", name: "car", src: Cars9 , cname : 'Cars9'},
  { category: "cars", name: "car", src: Cars10 , cname : 'Cars10'},
  { category: "cars", name: "car", src: Cars11 , cname : 'Cars11'},
  { category: "cars", name: "car", src: Cars12 , cname : 'Cars12'},
  { category: "cars", name: "car", src: Cars13 , cname : 'Cars13'},
  { category: "cars", name: "car", src: Cars14 , cname : 'Cars14'},
  { category: "cars", name: "car", src: Cars15 , cname : 'Cars15'},
  { category: "cars", name: "car", src: Cars16 , cname : 'Cars16'},
  { category: "cars", name: "car", src: Cars17 , cname : 'Cars17'},
  { category: "cars", name: "car", src: Cars18 , cname : 'Cars18'},
  { category: "cars", name: "car", src: Cars19 , cname : 'Cars19'},
  { category: "cars", name: "car", src: Cars20 , cname : 'Cars20'},
  { category: "cars", name: "car", src: Cars21 , cname : 'Cars21'},

  { category: "specific", name: "palace", src: Specific1 , cname : 'Specific1'},
  { category: "specific", name: "enviroment", src: Specific2 , cname : 'Specific2'},
  { category: "specific", name: "chair", src: Specific3 , cname : 'Specific3'},
  { category: "specific", name: "song", src: Specific4 , cname : 'Specific4'},
  { category: "specific", name: "galaxy", src: Specific5 , cname : 'Specific5'},
  { category: "specific", name: "enviroment", src: Specific6 , cname : 'Specific6'},
  { category: "specific", name: "photo", src: Specific7 , cname : 'Specific7'},
  { category: "specific", name: "city", src: Specific8 , cname : 'Specific8'},
  { category: "specific", name: "lake", src: Specific9 , cname : 'Specific9'},
  { category: "specific", name: "city", src: Specific10 , cname : 'Specific10'},
  { category: "specific", name: "lake", src: Specific11 , cname : 'Specific11'},
  { category: "specific", name: "lake", src: Specific12 , cname : 'Specific12'},
  { category: "specific", name: "valley", src: Specific13 , cname : 'Specific13'},
  { category: "specific", name: "colors", src: Specific14 , cname : 'Specific14'},
  { category: "specific", name: "forest", src: Specific15 , cname : 'Specific15'},
  { category: "specific", name: "galaxy", src: Specific16 , cname : 'Specific16'},
  { category: "specific", name: "dusk", src: Specific17 , cname : 'Specific17'},
  { category: "specific", name: "rock", src: Specific18 , cname : 'Specific18'},
  { category: "specific", name: "candle", src: Specific19 , cname : 'Specific19'},
  { category: "specific", name: "eye", src: Specific20 , cname : 'Specific20'},
  { category: "specific", name: "sky", src: Specific21 , cname : 'Specific21'},
];
